"""
gui/app.py
-----------
Desktop GUI for the Automatic Wall Crack Analyzer.

Built with Tkinter (zero extra install hassle on any lab/campus
machine — no PyQt wheel issues to fight during your demo). Structure:

  - Home tab: load an image, pick which algorithm to run, run pipeline
  - Processing Stages tab: click through every intermediate output
  - Measurements tab: crack length/width/area/damage %/confidence
  - Algorithm Comparison tab: loads reports/comparison_table.csv +
    graphs generated by evaluation/comparison.py (run that first on
    your dataset to populate this tab with real numbers)

Run with:  python gui/app.py   (run from the project root folder)
"""

import os
import sys
import tkinter as tk
from tkinter import ttk, filedialog, messagebox
from PIL import Image, ImageTk
import cv2

sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
import main as pipeline

STAGE_FOLDERS = [
    ("Original", None),
    ("Grayscale", "grayscale"),
    ("Enhanced", "enhanced"),
    ("Sobel", "sobel"),
    ("Prewitt", "prewitt"),
    ("Laplacian", "laplacian"),
    ("Canny", "canny"),
    ("Fusion (bonus)", "fusion"),
    ("Segmentation", "segmentation"),
    ("Morphology", "morphology"),
    ("Skeleton", "skeleton"),
    ("Final Annotated", "final"),
]


class WallCrackApp(tk.Tk):
    def __init__(self):
        super().__init__()
        self.title("AUTOMATIC WALL CRACK ANALYZER")
        self.geometry("1000x700")
        self.configure(bg="#1e1e2e")

        self.image_path = None
        self.image_id = None
        self.measurements = None
        self.selected_algo = tk.StringVar(value="canny")

        self._build_style()
        self._build_layout()

    def _build_style(self):
        style = ttk.Style(self)
        style.theme_use("clam")
        style.configure("TNotebook", background="#1e1e2e")
        style.configure("TNotebook.Tab", padding=(15, 8))
        style.configure("TFrame", background="#1e1e2e")
        style.configure("TLabel", background="#1e1e2e", foreground="#e0e0e0", font=("Segoe UI", 10))
        style.configure("Header.TLabel", font=("Segoe UI", 16, "bold"), foreground="#4C6EF5")
        style.configure("TButton", font=("Segoe UI", 10), padding=6)

    def _build_layout(self):
        header = ttk.Label(self, text="AUTOMATIC WALL CRACK ANALYZER", style="Header.TLabel")
        header.pack(pady=10)

        self.notebook = ttk.Notebook(self)
        self.notebook.pack(fill="both", expand=True, padx=10, pady=10)

        self.home_tab = ttk.Frame(self.notebook)
        self.stages_tab = ttk.Frame(self.notebook)
        self.measure_tab = ttk.Frame(self.notebook)
        self.compare_tab = ttk.Frame(self.notebook)

        self.notebook.add(self.home_tab, text="  Home  ")
        self.notebook.add(self.stages_tab, text="  Processing Stages  ")
        self.notebook.add(self.measure_tab, text="  Measurements  ")
        self.notebook.add(self.compare_tab, text="  Algorithm Comparison  ")

        self._build_home_tab()
        self._build_stages_tab()
        self._build_measure_tab()
        self._build_compare_tab()

    # ---------------- HOME ----------------
    def _build_home_tab(self):
        frame = self.home_tab

        ttk.Label(frame, text="1. Choose an algorithm to run:").pack(pady=(20, 5))
        algo_menu = ttk.Combobox(frame, textvariable=self.selected_algo,
                                  values=["sobel", "prewitt", "laplacian", "canny", "fusion"],
                                  state="readonly")
        algo_menu.pack()

        btn_frame = ttk.Frame(frame)
        btn_frame.pack(pady=20)
        ttk.Button(btn_frame, text="Upload Image", command=self.upload_image).grid(row=0, column=0, padx=5)
        ttk.Button(btn_frame, text="Analyze Image", command=self.analyze_image).grid(row=0, column=1, padx=5)

        self.home_preview = tk.Label(frame, bg="#2a2a3d")
        self.home_preview.pack(pady=10)

        self.status_label = ttk.Label(frame, text="No image loaded.")
        self.status_label.pack(pady=5)

    def upload_image(self):
        path = filedialog.askopenfilename(
            filetypes=[("Images", "*.jpg *.jpeg *.png *.bmp")]
        )
        if not path:
            return
        self.image_path = path
        self.image_id = os.path.splitext(os.path.basename(path))[0]
        self._show_image(path, self.home_preview, max_size=(500, 350))
        self.status_label.config(text=f"Loaded: {os.path.basename(path)}")

    def analyze_image(self):
        if not self.image_path:
            messagebox.showwarning("No image", "Please upload an image first.")
            return
        try:
            self.status_label.config(text="Running pipeline... please wait.")
            self.update_idletasks()
            final_img, measurements = pipeline.run_pipeline(
                self.image_path, chosen_algo=self.selected_algo.get()
            )
            self.measurements = measurements
            self.status_label.config(text="Analysis complete. See 'Measurements' and 'Processing Stages' tabs.")
            self._refresh_stages_tab()
            self._refresh_measure_tab()
        except Exception as e:
            messagebox.showerror("Error", str(e))
            self.status_label.config(text="Analysis failed.")

    # ---------------- STAGES ----------------
    def _build_stages_tab(self):
        frame = self.stages_tab
        control = ttk.Frame(frame)
        control.pack(pady=10)

        self.stage_var = tk.StringVar(value=STAGE_FOLDERS[0][0])
        stage_names = [s[0] for s in STAGE_FOLDERS]
        stage_menu = ttk.Combobox(control, textvariable=self.stage_var, values=stage_names, state="readonly", width=25)
        stage_menu.pack(side="left", padx=5)
        stage_menu.bind("<<ComboboxSelected>>", lambda e: self._show_stage())

        self.stage_preview = tk.Label(frame, bg="#2a2a3d")
        self.stage_preview.pack(pady=10, fill="both", expand=True)

    def _refresh_stages_tab(self):
        self._show_stage()

    def _show_stage(self):
        if not self.image_id:
            return
        stage_name = self.stage_var.get()
        folder = dict(STAGE_FOLDERS)[stage_name]

        if folder is None:
            path = self.image_path
        else:
            path = os.path.join("outputs", folder, f"{self.image_id}.png")

        if path and os.path.exists(path):
            self._show_image(path, self.stage_preview, max_size=(700, 450))
        else:
            self.stage_preview.config(image="", text="Not generated yet — run Analyze Image first.")

    # ---------------- MEASUREMENTS ----------------
    def _build_measure_tab(self):
        frame = self.measure_tab
        self.measure_text = tk.Text(frame, bg="#2a2a3d", fg="#e0e0e0", font=("Consolas", 12),
                                     height=20, width=80, relief="flat")
        self.measure_text.pack(padx=20, pady=20, fill="both", expand=True)
        self.measure_text.insert("1.0", "Run 'Analyze Image' on the Home tab to see results here.")
        self.measure_text.config(state="disabled")

    def _refresh_measure_tab(self):
        m = self.measurements
        crack_detected = m["area"]["crack_area_px"] > 0
        lines = [
            f"CRACK DETECTED: {'YES' if crack_detected else 'NO'}",
            f"Confidence Score: {m['confidence']}%",
            "",
            f"Lighting condition detected: {m['lighting_detected']}",
            f"Segmentation method used   : {m['segmentation_method']}",
            f"Reference-marker calibrated: {m['calibrated']}",
            "",
            "--- LENGTH ---",
            f"  {m['length']['length_px']} px"
            + (f"  (~{m['length']['length_cm']} cm)" if m['length']['length_cm'] else "  (no calibration marker found — pixel value only)"),
            "",
            "--- WIDTH ---",
            f"  Min: {m['width']['min_width_px']} px" + (f" (~{m['width']['min_width_cm']} cm)" if m['width']['min_width_cm'] else ""),
            f"  Max: {m['width']['max_width_px']} px" + (f" (~{m['width']['max_width_cm']} cm)" if m['width']['max_width_cm'] else ""),
            f"  Avg: {m['width']['avg_width_px']} px" + (f" (~{m['width']['avg_width_cm']} cm)" if m['width']['avg_width_cm'] else ""),
            "",
            "--- AREA / DAMAGE ---",
            f"  Crack area   : {m['area']['crack_area_px']} px" + (f" (~{m['area']['crack_area_cm2']} cm2)" if m['area']['crack_area_cm2'] else ""),
            f"  Wall area    : {m['area']['wall_area_px']} px",
            f"  Damage %     : {m['area']['damage_percentage']}%",
            "",
            "--- PROCESSING TIME (per algorithm, seconds) ---",
        ]
        for algo, t in m["timings_sec"].items():
            lines.append(f"  {algo:<12}: {t:.5f}s")

        text = "\n".join(lines)
        self.measure_text.config(state="normal")
        self.measure_text.delete("1.0", "end")
        self.measure_text.insert("1.0", text)
        self.measure_text.config(state="disabled")

    # ---------------- COMPARISON ----------------
    def _build_compare_tab(self):
        frame = self.compare_tab
        ttk.Button(frame, text="Reload comparison_table.csv", command=self._load_comparison).pack(pady=10)

        self.compare_tree = ttk.Treeview(frame, show="headings", height=8)
        self.compare_tree.pack(padx=20, pady=10, fill="x")

        self.graph_label = tk.Label(frame, bg="#2a2a3d")
        self.graph_label.pack(pady=10)

        self._load_comparison()

    def _load_comparison(self):
        import pandas as pd
        csv_path = os.path.join("reports", "comparison_table.csv")
        if not os.path.exists(csv_path):
            messagebox.showinfo(
                "No results yet",
                "reports/comparison_table.csv not found.\n\n"
                "Run evaluation/comparison.py on your dataset + ground-truth "
                "masks first (see Phase 9-10) to generate real comparison numbers."
            )
            return

        df = pd.read_csv(csv_path)
        self.compare_tree.delete(*self.compare_tree.get_children())
        self.compare_tree["columns"] = list(df.columns)
        for col in df.columns:
            self.compare_tree.heading(col, text=col)
            self.compare_tree.column(col, width=100)
        for _, row in df.iterrows():
            self.compare_tree.insert("", "end", values=list(row))

        graph_path = os.path.join("reports", "graphs", "f1_score_comparison.png")
        if os.path.exists(graph_path):
            self._show_image(graph_path, self.graph_label, max_size=(500, 350))

    # ---------------- HELPERS ----------------
    def _show_image(self, path, widget, max_size):
        img = Image.open(path)
        img.thumbnail(max_size)
        photo = ImageTk.PhotoImage(img)
        widget.config(image=photo, text="")
        widget.image = photo  # keep reference


if __name__ == "__main__":
    app = WallCrackApp()
    app.mainloop()
